import Head from 'next/head'
import Header from './Header'

interface Props {
  children: any
}

const Layout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>{children}</main>
    </>
  )
}

export default Layout
